language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -s UnitTest

branches:
  only:
      - gh-pages
      - /.*/